### ISSUE TITLE
`get_obs_surface` no available data behaviour

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#249]
What should be the behaviour when `get_obs_surface` can't find any data? I've just set it to return an empty `ObsData` object, does thi sound right?

**Comment by rt17603** [comment]
Yes I think returning some form of nothing would be best here. If/when we can log then this would be a good thing to add to a log but maybe a print statement for now to alert the user that nothing was found with the passed inputs?

Is ObsData.data being set to a None?

Personally I would prefer it returned None, because it's more clear that nothing was found - an empty ObsData object requires further investigation but if ObsData.data is being set to a None that might be clear enough.
