### ISSUE TITLE
Boundary condition file time error

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#349]
When trying to process `openghg/tests/data/boundary_conditions/co2_EUROPE_201407.nc` I get an error `TypeError: len() of unsized object`. This can be fixed with some try/excepts and using `time.values` instead of `time.values[0]` but there are also issues with chunking in the Datasource. Should we support files like this?

**Comment by rt17603** [comment]
If the issue that there is only 1 time point then I think we should support this because xarray sometimes does strange things where it reduces dimensions to 0. This happens when dimensions are squeezed.

For our use though, if we come across one of these zero-size dimensions we can expand the dimension back to 1 to be consistent and to get around the chunking etc.
