### ISSUE TITLE
" ValueError: Cannot match cabauw to a site code"

### ISSUE THREAD

**Issue by EricSaboya** [openghg/openghg#577]
### What happened?

I was attempting to add the attached observation files for Cabauw Tall Tower to my object store but received the following: `"ValueError: Cannot match cabauw to a site code" ` when running the following in an iPython terminal (see attached screenshot):

---------------------------------
    `from openghg.standardise import standardise_surface`
    `cbw = ('/user/work/wz22079/obs/cabauw.C', '/user/work/wz22079/obs/cabauw.precision.C')`
    `standardise_surface(cbw, source_format='GCWERKS', site='CBW', network='ECN', inlet='200m')`
---------------------------------

The following attempts to solve the bug were made:

1. Tried using "EUROCOM" or no network. -> Resulted in either same error or "network is a positional argument"

2. Checked all the data .json files in ~/openghg/data that relate to site codes of GCWERKS included "cabauw", they all did. NB. Some used "cabauw tower" as the short name, even when changing this to "cabauw" resulted in the same ValueError

Please note, as the standardise_surface function does not currently read .nc processed obs, I had to write a script to write the CBW output in a txt file format simil
[cabauw.C.txt](https://github.com/openghg/openghg/files/10812917/cabauw.C.txt)
[cabauw.precisions.C.txt](https://github.com/openghg/openghg/files/10812919/cabauw.precisions.C.txt)
ar to the GCWERKS output files for gcmd instruments. 
![site error](https://user-images.githubusercontent.com/44400065/220890856-4fb3d87d-1c77-4f53-9861-b9ff3aa3631e.png)

### Environment

<details>

</details>

**Comment by rt17603** [comment]
@EricSaboya - Just to comment on the statement

> "standardise_surface function does not currently read .nc processed obs"

If you mean that you've already processed the data into the netcdf format e.g. using acrg or otherwise then this can be read into openghg directly by passing `source_format="openghg"`. As long as the netcdf file matches to the expected standard then this should allow the data to be added.

This seems like something which is missing from the current documentation so will make sure we clarify that.

**Comment by rt17603** [comment]
So for reference this didn't work because Cabauw isn't included as one of the expected GCWERKS "sites" - this is set in the "openghg/data/process_gcwerks_parameters.json" file. This is presumably since this isn't one of the sites we would currently expect to process with the GCWERKS input parameter. Would you expect CBW to be accepted as a GCWERKS input? If not, I'll close this issue since we have a workaround.

**Comment by EricSaboya** [comment]
Happy for you to close this issue since we've got a workaround
