### ISSUE TITLE
Unable to retrieve HiTRes footprints from object store 

### ISSUE THREAD

**Issue by EricSaboya** [openghg/openghg#683]
### What is your issue?

When adding HiTRes CO2 footprints to the OpenGHG object store for certain times only the standard time resolution footprints are retrieved. 

An example of this problem is shown in this [https://github.com/EricSaboya/openghg_issues/blob/main/HiTRes_footprints_objectstore.ipynb](Jupyter notebook) - I couldn't upload the notebook with this issue

**Comment by rt17603** [comment]
Can I check, for the files you want to retrieve, can you see the files are available if you search?

**Comment by EricSaboya** [comment]
The HiTRes files don't appear in the search results for Mace Head (even without specifying the year)

**Comment by rt17603** [comment]
Can you see then if you search for ***all*** footprints - I'm wondering if it could be a labelling issue if you know you added them.

**Comment by EricSaboya** [comment]
Nope, I only see "standard_resolution" footprints when searching without any filters. The only HiTRes files that appear are the flux files I've added. It's strange because as shown in the Jupyter notebook I can retrieve the 2021-12 HiTRes footprints for Mace Head

**Comment by rt17603** [comment]
From discussion, we've identified a few points in the code that need fixing/connecting. Roughly this is covered by:

1. high_spatial_res, high_time_res ("time_resolution"), short_lifetime details need to be added to the required_keys within Footprints.read_file() 
2. Translation between any boolean values and sensible strings when adding to the metadata if needed 
3. Search_footprint needs to be looking for a string not a boolean

**Comment by brendan-m-murphy** [comment]
Currently it seems like the metastore doesn't contain the key "short_lifetime" by default, so 

1.  We can't make "short_lifetime" a required key, unless we change `datasource_lookup` to handle "short_lifetime" differently
2. We can't change "short_lifetime" in `search_footprints` to be a bool that defaults to false. (This was suggested by Gareth for "spatial_resolution", "time_resolution", and "short_lifetime"; it should be fine for the "resolution" parameters.)

Is the desired behaviour for `standardise_footprints` is that a new uuid is created if a species is short lifetime? If so, we need to include "short_lifetime" in the metastore, or change how `datasource_lookup` works.

**Comment by rt17603** [comment]
> Is the desired behaviour for `standardise_footprints` is that a new uuid is created if a species is short lifetime? If so, we need to include "short_lifetime" in the metastore, or change how `datasource_lookup` works.

Yes that is the desired behaviour, so this does need to be added in.

If that's going to take longer though to get this quickly fixed for this issue and for the 0.6.1 release though I think we should be putting in the quickest fix we can (adding in the "resolution" details) then adding in short_lifetime as the next stage immediately afterwards.

**Comment by gareth-j** [comment]
I think if we can we should add in `short_lifetime` to the `required_keys` at this stage. That is unless it'll break someone's workflow, has anyone been adding in short lifetime footprints to the shared object store?

**Comment by rt17603** [comment]
> I think if we can we should add in `short_lifetime` to the `required_keys` at this stage. That is unless it'll break someone's workflow, has anyone been adding in short lifetime footprints to the shared object store?

I'm just very keen to make sure this goes in asap as this is something which has been needed for a while. If it takes no less time, then fine yes add it in now, but otherwise I think we need to briefly prioritise getting in the necessary workflow.

**Comment by brendan-m-murphy** [comment]
I can add "short_lifetime" to required keys. I need to make its values "true" or "false" as strings, or else the netcdf backend complains. (Python's json module decodes "true" to True and "false" to False by default, so lower case "true"/"false" might make life easier. I'm not sure if that means TinyDB will convert them to Booleans though.)

This shouldn't take much longer to implement since I need to find data to test "high_spatial_resolution" anyway, so I can do "short_lifetime" at the same time.

If we're making changes that require the object store to be re-populated with footprints, we could also change the metastore/netcdf metadata at the same time to use booleans for the "resolution" variables. On the other hand, it might be worth taking some time to write down a specification for what/how metadata is stored in the metastore and as attributes in the netcdf files. (I guess some of this is in the schemas? But it might be nice to have more documentation.)

**Comment by rt17603** [comment]
> I can add "short_lifetime" to required keys. I need to make its values "true" or "false" as strings, or else the netcdf backend complains. (Python's json module decodes "true" to True and "false" to False by default, so lower case "true"/"false" might make life easier. I'm not sure if that means TinyDB will convert them to Booleans though.)

This was a question I asked previously (though looks like not on this issue discussion thread) - can we add booleans directly when saving the metadata? If the answer is no, then we do need to think about the user interface for this - we want it be really easy to add and retrieve this data with clear and consistent keywords. What I'm saying is, whatever keywords are included for `standardise_footprint` should be the same as `search_footprint` otherwise it just gets confusing.

Question: for this setup would the user need to pass `search_footprint(..., high_time_res="true")` to get the high time resolution footprints?

**Comment by brendan-m-murphy** [comment]
> whatever keywords are included for standardise_footprint should be the same as search_footprint otherwise it just gets confusing.

I agree. With the changes I've made so far, you can search for high time resolution either by giving `high_time_res=True` or `time_resolution="high_time_resolution"` to `search_footprints`. The same logic should work for spatial resolution, but I haven't made the tests yet.

Previously, `high_time_res=True` didn't do anything, and the option `time_resolution="high_time_resolution"` wasn't in the docstring, but it would have the right effect if you added it to the optional keywords. Now you can use both.

On the other hand, for `standardise_footprints`, currently  there is no way to give `time_resolution="high_time_resolution"` as an argument, and you need to use `high_time_res=True`.

So right now, standardising and search can both use the Boolean option "high_time_res", but in the metastore, it is saved as "time_resolution": "high_time_resolution" (or "standard_time_resolution"). So, from the users end, if they don't inspect the metastore, standardising and searching use the same arguments, although you could also pass the kwarg for time resolution in search, if you wanted to.

I can drop the kwarg option in search, then the interfaces are exactly the same. Although the metastore, and possibly the netcdf attributes, will use "time_resolution".

> Question: for this setup would the user need to pass search_footprint(..., high_time_res="true") to get the high time resolution footprints?

Yes, although we could add some logic to `search_footprints` to infer high time resolution from `species="co2"`, or similar.

**Comment by gareth-j** [comment]
We can add booleans when saving the metadata, just not to the NetCDF attributes. 
And yeah we definitely need the same arguments passed into `standardise_footprint` and `search_footprint`.
Shall we:
1. Pass booleans to the functions
2. Write attrs["high_time_resolution"] = "True" to the NetCDF attributes 
3. Ensure `sync_surface_metadata` is the doing the right thing and not adding any booleans to the attributes

The NetCDF attributes shouldn't be saved as JSON so the "True" and "False" strings should be OK.

**Comment by gareth-j** [comment]
Why will the metastore will still use `time_resolution`? The metastore should only contain the data that's added to the metadata. If should only contain the bools passed into the standardise function. If we're expected the data to be read in again we can remove my suggestion from #717 

```
time_resolution = "high_time_resolution" if high_time_res else "standard_time_resolution"
spatial_resolution = "high_spatial_resolution" if high_spatial_res else "standard_spatial_resolution"
```
Would now just become

```
metadata["high_time_res"] = bool
metadata["high_spatial_res"] = bool
# And adding in this
metadata["short_lifetime"] = bool
```

**Comment by brendan-m-murphy** [comment]
When standarising, eventually `set_object_from_json` calls `json.dumps`, which will convert `True` to `"true"`, so maybe we want to have lowercase true/false everywhere? I guess it doesn't really matter if the netcdf attributes match the metastore though. (Also, does TinyDB not have any commands for adding data? I only really glanced at the docs.)

@gareth-j  your plan sounds good. I don't really understand point 3, but I'll just look at that function and see what it's doing.

Should the "time_resolution" and "spatial_resolution" kwargs just be ignored then? (E.g., I won't convert them to have the same effect as "high_time_res" and "high_spatial_res".)

**Comment by brendan-m-murphy** [comment]
> Why will the metastore will still use `time_resolution`? The metastore should only contain the data that's added to the metadata. If should only contain the bools passed into the standardise function. If we're expected the data to be read in again we can remove my suggestion from #717
> 
> ```
> time_resolution = "high_time_resolution" if high_time_res else "standard_time_resolution"
> spatial_resolution = "high_spatial_resolution" if high_spatial_res else "standard_spatial_resolution"
> ```
> 
> Would now just become
> 
> ```
> metadata["high_time_res"] = bool
> metadata["high_spatial_res"] = bool
> # And adding in this
> metadata["short_lifetime"] = bool
> ```

I guess I didn't think we were changing the metastore originally, so I made both options supported. (Converting the boolean versions to the string versions, since that was what is currently in the metastore.)

I'll push a draft PR so you can see what I have so far.

**Comment by brendan-m-murphy** [comment]
Anyway, a solution would be to convert any strings of the form "true" or "false" to Booleans before comparing. (Although right now I'm not very clear on exactly what is happening in `sync_surface_metadata`.)

I'll run all the standardising and search tests as I work on the footprints stuff to see if anything breaks.

**Comment by rt17603** [comment]
> Is this what Gareth put as point 3. above: `sync_surface_metadata` ? It's not clear to me where `assign_attributes`, `get_attributes`, and `sync_surface_metadata` (and calls from `standardise.surface` like `parse_gcwerks` in `_gcwerks.py`) are actually pulling metadata from the metastore.
> 
> For `parse_gcwerks` it looks like some metadata is created and compared with attributes from some xarray Dataset. Is the metadata created meant to be the same as what would be added to the metastore?
> 
> Are there future plans to implement something similar for footprints?

 - Yes, `sync_surface_metadata` is currently only applied to the surface data but we will want this logic to be applied to attributes for all data types in the long term.
    - As another point `assign_attributes`, `get_attributes` *aren't pulling* metadata from the metadata, they're used to define and then *add* data to the metastore.
 - The metadata is what is added to the metastore
 - Yes, as we were discussing last week there's no real reason for attributes to be treated differently for the different data_types - they should largely be funneled along the same pipeline and have the same checks. In fact there is a specific issue for footprints raised by Elena already - #514

**Comment by brendan-m-murphy** [comment]
Okay, so:
1. data and metadata are read from files (e.g. by `_read_data` in `_gcwerks.py`)
2. `assign_attributes` parses some of this metadata and passes it to `get_attributes`
3. `get_attributes` modifies the data (Dataset) using some of the arguments passed from `assign_attributes` (and adding stuff without reference to the arguments passed by `assign_attributes`?)
4. `assign_attributes` gets the modified data back from `get_attributes` then passes the original metadata passed to `assign_attributes` and the attributes of the modified data to `sync_surface_metadata`
5. `sync_surface_metadata` compares the values in the metadata and attributes for common keys, and might update them or ignore mismatches depending on the value of `overwrite_mismatch`, which you can specify in `standardise_surface`
6. `standardise_surface` calls the parser function (e.g. `parse_gcwerks`) which returns the "aligned" metadata that matches the attributes of the data returned from the parser
7. the metadata returned from the parser is added to the metastore

Also around steps 3 and 4, the changes made to the metadata are to ensure compliance with CF standards.

It would be nice to simplify this, but that should probably be another issue. Is it written this way because there can be some keys that are in the metastore that shouldn't be in the attributes, and some keys that are in the attributes of the input data that shouldn't be in the metastore? (e.g. optional search keywords in the metastore and extra info attached to the input data)

It seems like it ought to be possible to
1. collect, clean, combine, and make compliant all metadata (e.g. from user input and input files)
2. set the attributes of the data file based on this combined metadata
3. set the metadata for the metastore based on this combined

The current process does this, but parts are intertwined. I guess optional or "unexpected" metadata might be problematic, but we can track its source, and e.g. if it was in the input data, add it to the attributes in step 2.

**Comment by rt17603** [comment]
Looks good - could you transfer this part of the discussion to #708 ?

**Comment by rt17603** [comment]
One comment I would make is that the attributes and metadata serve different purposes which is why we have both - so as I said the values should align for the same keys but they don't have to include all of the same keys.
