### ISSUE TITLE
Object store lockfile

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#695]
So we don't encounter issues with a single data storage class being used by multiple people at the same time we should get them to check for the existence of a lockfile at the start of their `read_file` functions. Something like

```
# Checks if the lockfile exists for this object in the bucket
self._set_lock()
# do some work and assign the data
self._release_lock()
```

**Comment by gareth-j** [comment]
Christopher suggested a lockfile that is owned by a user and has to be released within a certain reasonable timescale. 
"Once solution is saying that commits have to be made within a specified time delta of the lock. So, the lockfile records the time it was set, and it that time passes then the lock is automatically removed and the user holding the lock can no longer commit the change."

**Comment by gareth-j** [comment]
As we drive to the Datasources as we go, if we encounter an error maybe we could do with some kind of rollback feature that restores the store to its previous state? Or at least the Datasources to their previous state.

**Comment by brendan-m-murphy** [comment]
This doesn't say how they implement these controls, but the psycopg "connection" class has these features: https://www.psycopg.org/docs/usage.html#transactions-control. (psycopg is a Python SDK for postgresql)

Maybe we need a "connection" context for datasources that stages changes somewhere, and on exit, either discards the changes if there was an error (including conflicting writes?), or commits the changes.

We could combine this with a lockfile package: https://pypi.org/project/fasteners/ or https://docs.openstack.org/oslo.concurrency/latest/. 

(Also, I don't know why I like "connection" as a context name so much... maybe we could just have an "open_datasource" context.)

**Comment by brendan-m-murphy** [comment]
The alternative to discarding changes when another write has occurred before you complete a write-transaction would be to have multiple versions, but we would need to manually merge them or maybe have a system where the version you created is the one that you get back in search by default.

If we only write chunks when changes are made (rather than modifying files in place), then a version can be a list of certain file uuids, rather than a directory of files. Then, like in a git, each version can point to its parent, so we can see a history graph. (Maybe a dumb way to do this is to make "versions" CSVs with one line for each possible chunk over 20-30 years, along with the time and user that updated each chunk. Then track these files in a git repo.)

**Comment by brendan-m-murphy** [comment]
I guess then to delete a version, we just need to collapse the history and discard unused files, and merging could be creating a new common version (and optionally deleting the files that aren't kept).

**Comment by chryswoods** [comment]
This is the same issue as #765
