### ISSUE TITLE
Default sampling period for modules

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#71]
Should we have a default sampling period for modules or insist on it being passed in by the user / read somehow?

Currently the BTT, Cranfield, EUROCOM modules need looking at.

**Comment by rt17603** [comment]
BTT (BT Tower) - the sampling period seems to be 30 minutes for this (file naming and looking at the data itself).
Cranfield data - the sampling period seems consistently be 5 seconds for the data present.

For EUROCOM it may depend on which data falls into that category - where were you grabbing your EUROCOM data from?

For CRDS and GCWERKS these sampling periods were being derived from an underlying json file - do we want to adopt a similiar approach for all modules where possible?

**Comment by rt17603** [comment]
On the question of a default sampling period, I think we decided we can have one on a case-by-case basis (like we're doing at the moment with having a "sampling_period" defined in json files) but we don't want to have a universal value for these files.

I think this may become information we need in advance when putting together the different data processing modules rather than asking the user to input this but we can leave allowing this as an input for now.

**Comment by gareth-j** [comment]
Add the jinja2 pinning and retry test runners.
