### ISSUE TITLE
Remove `object_store` from Datasource metadata

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#723]
Shall we just remove the `object_store` key from the Datasource metadata?
I can see it causing issues if a user moves their store or changes the foldername.
We should just be able to read Datasources from an object store without this information using the search function.
We can then add in the object store path to the metadata on retrieval.

**Comment by rt17603** [comment]
Having the "object_store" key adds traceability but you're right in principle we should just be able to add this when the data and metadata are extracted.

If you feel removing the "object_store" key makes this feel a bit less prone to potential error due to mismatch, I'd be happy to go with that.

**Comment by brendan-m-murphy** [comment]
If there is logging info when a datasource is created, we could say what object store the datasource was added to. (E.g. "created in {object_store} object store".) I don't think this info should be updated though.

But I think it make sense to just extract this info when searching, rather than keeping it in metadata. Otherwise it is just a piece of metadata that could become false, and we'd have to find a way to keep it updated.
