### ISSUE TITLE
When updating metastore, update temp version and then update metastore when finished

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#764]
### Is your feature request related to a problem?

At the moment, when the metastore is updated this is loaded into memory and written to directly. This means that read processes (e.g. searches) may fail while the data is being updated.

For write processes, for multiple users (or multiple processes from one user) this also means multiple processes could be trying to update the same data and cause corruption. (This is also being addressed by #695 to make sure the file is locked while updates are happening). This is related to #748

### Describe the solution you'd like

Move to loading a temporary version of the metastore into memory, updating this and then updating the stored metastore in one move at the end.

### Describe alternatives you've considered

Longer term we may want to move to a proper underlying database and document store - see #756

### Additional context

This needs to happen alongside #695

**Comment by brendan-m-murphy** [comment]
Since writes (to disk) will probably be pretty fast, before writing to the metastore, we can "pull" the metadata, and check for changes.  If there are conflicting changes, then maybe we can raise an error, otherwise, merge the metadata and write. This isn't totally safe, but should at least help if someone is standardising data and someone else updates some metadata while the data is being standardised.

**Comment by rt17603** [comment]
If we combine with a lock file then would there be expected circumstances where "there are conflicting changes"?

**Comment by brendan-m-murphy** [comment]
Gareth was proposing lock files for datasources I think, in which case it would be possible. A lock file for the entire metastore would be fairly limiting, although we could do it for now. (I meant to ask Christopher this week, but in the meeting two weeks ago, he suggested that file locks might not work so well on BP because it uses NFS instead of a normal file system.)

A file lock on the entire metastore would mean that files can't be processed in parallel, since with Python, we need to start a new process for each CPU core we want to use, and those processes would be competing for locks. A single node on BP has 20-30 cores, which is a lot of power we're missing out on.

**Comment by brendan-m-murphy** [comment]
The scenario I'm thinking of is Alice uploading footprints for different species. Those are different datasources, so a lock on datasources could be okay, but a lock on the Footprints metastore means the data can't be standardised in parallel.

**Comment by brendan-m-murphy** [comment]
Oh nevermind, Gareth said acquiring locks at the start of `read_file`, which would be when the metastore is accessed. So, no, it's not possible that someone can update metadata during standardisation in that case. Although it does mean parallel processing isn't possible, unless we can somehow pass the lock to processes spawned by someone holding the lock.

**Comment by rt17603** [comment]
I think we need to really consider what our expected workflows are. After the initial setup, the standardisation and adding to the object store would not be so regular and would include less data. Once we've gone through the initial step of adding the footprints for instance, additions would be smaller. Measured data would be updated more regularly but would likely comprise smaller files.

I'm not sure we need to be able to standardise data (or at least add data to the store) in parallel - that would be hard for any data system. Our issue at the moment is that it's taking so long but that would at least be improved by the plans we have for better compression and more efficient processes.

I guess I'm asking, in the short term do we need parallel processing?

**Comment by brendan-m-murphy** [comment]
If writes to the metastore could happen concurrently (e.g. the nice merge scenario above where there aren't conflicting changes), then we could implement parallel processing fairly easily: https://docs.python.org/3/library/concurrent.futures.html

You
1) create a Process Pool with some workers
2) put the standardising tasks in a queue
3) have the workers consume the queue

It's basically that instead of a for-loop, assuming the standardising tasks don't interact. So for the type of batch job Alice was doing, we could parallelize it, since the datasources wouldn't conflict.

I don't know if we need it, but it does seem like it was wasting a lot of Alice's time. (Like 24 hours per year of footprints for 30 sites... that could be less than an hour on BP.) I guess there could be memory issues, but for what Alice was doing, there really shouldn't be any previously added footprints in memory, since they only need to be read if the date ranges conflict, so each process probably only needs 20-30GB of memory.
