### ISSUE TITLE
When adding footprints does not currently differentiate between metmodel

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#903]
### What happened?

Specifying different `metmodel` input does not create different data sources. One thing to consider is this is an optional input and so is not always specified (which may make this a bit more complex when adding new data and checking if the current datasource exists).

For example:
- /group/chemistry/acrg/LPDM/fp_NAME/EUROPE/MHD-10magl_EUROPE_201112.nc
- /group/chemistry/acrg/LPDM/fp_NAME/EUROPE/MHD-10magl_UKV_EUROPE_201201.nc

See similarly #902 

### What did you expect to happen?

Two datasources to be created rather than one combined datasource.

### Minimal Complete Verifiable Example

Running on BP1

```Python
from openghg.standardise import standardise_footprint
from pathlib import Path

directory = Path("/group/chemistry/acrg/LPDM/fp_NAME/EUROPE")

store = "user"

file_nometmodel = directory / "MHD-10magl_EUROPE_201112.nc"
file_metmodel = directory / "MHD-10magl_UKV_EUROPE_201201.nc"

site = "MHD"
inlet = "10m"
domain = "EUROPE"
model = "NAME"

standardise_footprint(file_nometmodel,
                      site=site,
                      inlet=inlet,
                      domain=domain,
                      model=model,
                      store=store)


metmodel = "UKV"

standardise_footprint(file_metmodel,
                      site=site,
                      inlet=inlet,
                      metmodel=metmodel,
                      domain=domain,
                      model=model,
                      store=store)


#%%

from openghg.retrieve import search_footprints

footprints = search_footprints(store=store, site="mhd").results

print(footprints)
print(footprints["metmodel"])
```

### Relevant log output

```Python
(openghg_devel) [rt17603@bp1-login02 openghg]$ /user/work/rt17603/environments/openghg_devel/bin/python /user/home/rt17603/Code_BP1/OpenGHG/Test_footprint_add_metmodel_keys.py 
    data_type site  ... metmodel                        object_store
0  footprints  mhd  ...      ukv  /user/work/rt17603/test_store_zarr

[1 rows x 24 columns]
0    ukv
Name: metmodel, dtype: object
```

**Comment by brendan-m-murphy** [comment]
A few points from the architecture meeting:

1. all key/value formatting for metadata and search terms should happen as centrally as possible. 

`TinyDBMetaStore` already has an internal method `_format_metadata`, which is used before searching for data and inserting new data. (I noticed that it should also be called on `to_update` in the update method...). 

In `_classic_metastore.py`, the `open_metastore` function uses a `TinyDBMetaStore` and `DataClassMetaStore` subclasses `TinyDBMetaStore` (adding file locks). If we make a subclass like `FormattedMetaStore` and just override `_format_metadata` (plus fixing the update issue), we can format the values for search, insert, and update in one place.

We may want to format metadata before processing it, so perhaps we need a general utility function that takes a dictionary and formats the keys and values, then use this in our `FormattedMetaStore` (or whatever we want to call it).

(Another option is to make the formatting function a parameter and pass it to the constructor of `TinyDBMetaStore`. I supposed I'd prefer to keep `TinyDBMetaStore` more generic though. 

2. `open_metastore` should probably be read only

...and all writes should go through `DataClassMetaStore` (e.g. in data manager as well as `BaseStore`). Alternatively, we should modify `open_metastore` so that it uses file locks in "rw" mode (probably the better option)

3. `BaseStore` currently uses `DataClassMetaStore` so that it can use file locks

This set-up isn't idea. Part of the issue is that we want to make sure that the results of `datasource_lookup` are still valid after the data has been parsed. So we want to acquire the lock before `datasource_lookup` and only release it after the data is assigned.

Another way to accomplish this would be to make the metastore an argument that gets passed to `datasource_lookup`; then we could call `open_metastore` in "rw" mode (with a lock , if we add this feature), and pass the metastore to `datasource_lookup`.

4. `retrieve.search` and `assign_data` should use the metastore directly

`retrieve.search` is mean to parse the search terms and the search results returned, `assign_data` needs to check the metastore via `datasource_lookup`. You _could_ use `search` to perform the datasource lookup, but the only reason to do this would be consistency in parsing search terms, which should be handled by point 1.

If there are features of `retrieve.search` that would be generally useful for searching, I suggest we implement them in a subclass of `TinyDBMetaStore`. 

5. tinydb has a lot more search options than we're currently using:

https://tinydb.readthedocs.io/en/latest/usage.html#queries

including: checking for the existence of a key, negating a query, searching for "any" or "all" over a list of values.

We could make it possible to pass tinydb `Query` objects to search, which would allow us to do more complex searches.

e.g. if `metmodel=np.nan` is passed to search, we could translate that to `~ (tinydb.Query().metmodel.exists())` and then combine that with our search fragment.

6. we could add optional keywords to `datasource_lookup`

if "required" and "optional" keywords can be loaded from a config file, then we can provide a way to add optional keywords to this config file. If you do this, and you pass a non-`None` value to an optional keyword, then it is used in datasource lookup. Any missing optional keywords in datasource lookup can be filled with `np.nan`, meaning we specifically want to create a datasource without they keys.

We should probably have some logging information saying exactly what has happened (say by also searching without the missing optional keys with `np.nan` values, and alerting the user that a datasource *not* using those keywords has been created).

**Comment by rt17603** [comment]
As we're recreating the object stores anyway, can fix this in a simple way by including "NOT_SET" as keyword when this is not specified. Issue #956 created to address comment above and will need to allow for optional keywords as another step for this.
